version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application -w 3 --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file: 
      - env/app
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:10.4
    env_file: 
      - env/db
    ports:
      - 5432:5432
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./volumes/backups:/backups
    links:
      - db:db
    depends_on:
      - db
    env_file: 
      - env/backups
volumes:
  static_volume:
  media_volume:
