# Generated by Django 3.1 on 2022-01-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=256)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
