name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploying to server
      uses: appleboy/ssh-action@master # An action made to control Linux servers
      with: # We set all our secrets here for the action, these won't be shown in the action logs
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd medusa-light # we move into our app's folder
          git pull # we pull any changes from git
          docker-compose exec -T web python manage.py migrate
          docker-compose restart web nginx
